// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsBSDKTqVDctu2oQ95aRCJ_uk6BklwuV0',
    appId: '1:1089326663797:web:76661db4a9a15d7307d03c',
    messagingSenderId: '1089326663797',
    projectId: 'vitalize-9ce5d',
    authDomain: 'vitalize-9ce5d.firebaseapp.com',
    storageBucket: 'vitalize-9ce5d.appspot.com',
    measurementId: 'G-E2SRP24XVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZBnrRU9m80JoLWOr-JOq9EL6-p5B6Prw',
    appId: '1:1089326663797:android:57c6bfb6b752ecc207d03c',
    messagingSenderId: '1089326663797',
    projectId: 'vitalize-9ce5d',
    storageBucket: 'vitalize-9ce5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXTtEJMR5urVmsPFpz7jcOKZIeijyjMEQ',
    appId: '1:1089326663797:ios:4af72558afd7e7e207d03c',
    messagingSenderId: '1089326663797',
    projectId: 'vitalize-9ce5d',
    storageBucket: 'vitalize-9ce5d.appspot.com',
    iosBundleId: 'com.example.vitalize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXTtEJMR5urVmsPFpz7jcOKZIeijyjMEQ',
    appId: '1:1089326663797:ios:4af72558afd7e7e207d03c',
    messagingSenderId: '1089326663797',
    projectId: 'vitalize-9ce5d',
    storageBucket: 'vitalize-9ce5d.appspot.com',
    iosBundleId: 'com.example.vitalize',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsBSDKTqVDctu2oQ95aRCJ_uk6BklwuV0',
    appId: '1:1089326663797:web:f0ae3b44d4fcf78307d03c',
    messagingSenderId: '1089326663797',
    projectId: 'vitalize-9ce5d',
    authDomain: 'vitalize-9ce5d.firebaseapp.com',
    storageBucket: 'vitalize-9ce5d.appspot.com',
    measurementId: 'G-REKQ5MKKBY',
  );
}
