name: vitalize
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

fonts:
  - family: Billabong
    fonts:
      - asset: assets/fonts/Billabong.ttf

dependencies:
  flutter:
    sdk: flutter
  app_links: ^6.3.3
  flutter_blue_plus: ^1.33.4
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.0
  image_picker: ^1.1.2
  file_picker: ^8.1.4
  http: ^1.2.2
  fl_chart: ^0.70.0
  intl: ^0.19.0
  flutter_vector_icons: ^2.0.0
  datetime_picker_formfield_new: ^2.1.0
  firebase_storage: ^12.4.0
  firebase_analytics: ^11.4.0
  percent_indicator: ^4.2.3
  shared_preferences: ^2.3.2
  supabase_flutter: ^2.8.0
  font_awesome_flutter: ^10.7.0
  linear_gradient: ^0.1.13
  shimmer: ^3.0.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  health: ^11.1.1
  permission_handler: ^11.3.1
  logger: ^2.4.0
  google_sign_in: ^6.2.2
  fdevs_fitkit: ^0.0.1+3
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  timeago: ^3.7.0
  google_maps_flutter: ^2.10.0
  stop_watch_timer: ^3.2.1
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  animations: ^2.0.11
  flutter_dotenv: ^5.2.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  conditional_builder_null_safety: ^0.0.6
  skeletonizer: ^1.4.2
  smooth_page_indicator: ^1.2.0+3
  flutter_styled_toast: ^2.2.1
  flutter_appauth: ^8.0.3
  path_provider: ^2.1.5
  path: ^1.9.1
  video_player: ^2.9.2
  chewie: ^1.9.0
  mime: ^2.0.0
  cached_network_image: ^3.4.1
  vibration: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/map_style.json
    - assets/icons/

